#!/bin/sh
set -e
######## KTLINT FORMAT START ########

#    CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $NF ~ /\.kts?$/ { print $NF }')"
    CHANGED_FILES="$(git --no-pager diff HEAD --name-status --no-color | awk '$1 != "D" && $NF ~ /\.kts?$/ { print $NF }')"

    echo "Running ktlint over these files:"
    echo "$CHANGED_FILES"

    ./gradlew ktlintFormat -PinternalKtlintGitFilter="$CHANGED_FILES"

    echo "Completed ktlint run."

######## KTLINT FORMAT END ########
